#!/bin/bash

# This script controls the sound settings. It will get the requested level in
# $1.
#
# It is up to the script to control all the sound channels.
CHANNEL="Master"

function get_max {
	set -- $(amixer sget $CHANNEL | grep 'Limits:')
	return $5
}

# Main
#
# Level is in $1
#
case "$1" in
	"0")	# Mute sound
		amixer set $CHANNEL 0 >/dev/null
		;;

	"1")	# Set minimum level 
		get_max
		amixer set $CHANNEL $(($?/2)) >/dev/null
		;;

	"2")	# Set medium level
		get_max
		amixer set $CHANNEL $(($(($?/3))*2)) >/dev/null
		;;

	"3")	# Set maximum level
		get_max
		amixer set $CHANNEL $? >/dev/null
		;;

	*)
		echo "Usage: $0 0|1|2|3"
		exit 1
		;;
esac
exit 0
