.TH GIFTRANS 1

.SH NAME
giftrans \- manipulate transparency in .gif files

.SH SYNOPSIS
.B giftrans
[-C] [-c rrggbb] [-h] [-i index] [-v]
.br

.SH DESCRIPTION
.B giftrans
can clear and set the transparency index in gif files.
  
.SH OPTIONS
.PP
.TP
.I "\-C"
Clear transparency.
.BR
.TP
.I "\-c rrggbb"
Set the transparency index to the color closest to rrggbb.
.BR
.TP
.I "\-h"
Show help text.
.BR
.TP
.I "\-i idx"
Set the transparency index to idx.
.BR
.TP
.I "\-v"
Show version information.
.BR

.SH AUTHOR
Brian Schau <brian@schau.dk>
