#!/usr/bin/env php
<?php
	$minW=false;
	$maxW=false;
	$minH=false;
	$maxH=false;

	for ($i=1; $i<$argc; $i++) {
		if (file_exists($argv[$i])) {
			list($w, $h, $t, $a)=getimagesize($argv[$i]);
			echo $argv[$i].": ".$w." x ".$h."\n";
			if (($minW==false) || ($w<$minW)) {
				$minW=$w;
			}
			if (($maxW==false) || ($w>$maxW)) {
				$maxW=$w;
			}
			if (($minH==false) || ($h<$minH)) {
				$minH=$h;
			}
			if (($maxH==false) || ($h>$maxH)) {
				$maxH=$h;
			}
		} else {
			echo $argv[$i].": no such file\n";
		}
	}

	echo "minW: ".$minW."  maxW: ".$maxW."  minH: ".$minH."  maxH: ".$maxH."\n";
?>
