#!/bin/bash
#ROOT="/home/bs/Workspace"
REPOACCOUNT="git@github.com:bschau"
REPOS="bschau.github.io Configurations Ethereum GameDev kwed-dl Portfolio VPSApps Webs"
rsync_flags="-rvz -zz --progress --omit-dir-times --size-only --delete --exclude=.Spotlight-V100 --exclude=.DocumentRevisions-V100 --exclude=.DS_Store --exclude=.fseventsd --exclude=.Trashes --exclude=.TemporaryItems --exclude=.git --exclude=.gitignore --exclude=.gd --exclude=*~ --exclude=node_modules"

function _usage
{
	echo "Usage: repo checkout | rsync | status" >&2
	exit $1
}

function _checkout
{
	repo="$1"
	account="$2"

	if test -d "$repo"; then
		echo "Updating $repo ..."
		cd "$repo"
		git pull
	else
		echo "Cloning $repo ..."
		git clone "$account"
	fi
}

function _status
{
	repo="$1"
	if test ! -d "$repo"; then
		echo "$repo not found" >&2
	else
		cd "$repo"
		echo -n "$repo"
		status="$(git status --porcelain)"
		if test -z "$status"; then
			echo "... OK"
		else
			echo "... DIRTY"
			echo
				echo "$status"
			echo
		fi
	fi
}

function _rsync
{
	echo "Syncing to rsync ..."
	remote="${RSYNCACCOUNT}:GitHub"
	cd "$root"
	rsync $rsync_flags --rsh=ssh "." "${remote}/"
}

if test $# -eq 0; then
	_usage 0
fi

if test -z "$REPOACCOUNT"; then
	echo "No REPOACCOUNT (default account) set" >&2
	exit 1
fi

root="${ROOT:=$HOME/Workspace}"
if test ! -d "$root"; then
	echo "$root not found or not a directory" >&2
	exit 1
fi
export root

cmd="$1"
shift

case "$cmd" in
	"checkout"|"status")
		cmd="_$cmd" ;;
	"rsync")
		if test -z "$RSYNCACCOUNT"; then
			echo "RSYNCACCOUNT not set" >&2
			exit 1
		fi
		_rsync
		exit 0
		;;
	*)
		_usage 0 ;;
esac

if test $# -eq 0; then
	repos="$REPOS"
else
	repos="$*"
fi

oldIFS="$IFS"
for r in $repos; do
	cd "$root"

	IFS="/"
	set -- $r
	repo="$1"
	account="$2"
	IFS="$oldIFS"

	if test -z "$account"; then
		account="$REPOACCOUNT"
	fi

	account="${account}/${repo}"
	$cmd "$repo" "$account"
done

exit 0
