.TH D2U 1

.SH NAME
d2u \- convert from DOS to unix

.SH SYNOPSIS
.B d2u
file1 file2 ... fileN
.br

.SH DESCRIPTION
.B d2u
converts DOS linefeeds ('\\r\\n') to unix linefeeds ('\\n').

.SH NOTE
There are numerous tools like this. All of them are better than d2u. Use the
other tools, please.

.SH AUTHOR
Brian Schau <brian@schau.dk>
