.TH JPGINFO 1

.SH NAME
jpginfo \- show sizes of jpegs as well as maximum and minimum sizes

.SH SYNOPSIS
.B jpginfo
[\fI-h\fR] jpg1 jpg2 ... jpgX
.br

.SH DESCRIPTION
.B jpginfo
show the size of the individual jpg file and keep track of maximum and minimum sizes.

.SH OPTIONS
.TP
\fB-h\fR
Show a brief help page.
.TP
\fB-n\fR
Do not keep track of maximum and minimum sizes.

.SH AUTHOR
Brian Schau <brian@schau.dk>
