.TH WI 1

.SH NAME
wi \- where is file?

.SH SYNOPSIS
.B wi
[-d] [-e] [-h]
.br

.SH DESCRIPTION
.B wi
looks for the specified file or directory in the current directory and any
child directories below the current directory.
  
.SH OPTIONS
.PP
.TP
.I "\-d"
Look for directory.
.BR
.TP
.I "\-e"
Match exact case.
.BR
.TP
.I "\-h"
Help page.
.BR

.SH AUTHOR
Brian Schau <brian@schau.dk>
