.TH WMMUTE 1L "27 December 2016"
.SH NAME
wmmute \- dock application to control sound settings

.SH SYNOPSIS
.B wmmute
[\fI-c helper\fR] [\fI-h\fR] [\fI-l level\fR]

.SH DESCRIPTION
wmmute is a dock application which can control the sound settings. It can set the loudness of the sound in 4 steps: mute, minimum, medium and maximum. The actual setting of the loudness is done in the wmmute-helper program or the program supplied by the -c argument.

.SH OPTIONS
.TP
\fB-c helper\fR
Helper program. Default is wmmute-helper.
.TP
\fB-h\fR
Show a small help page.
.TP
\fB-l level\fR
Sound level. Default is 0 (muted). Other levels are 1 (minimum), 2 (medium) and 3 (maximum).

.SH HELPER
The helper program does most of the work. The default program is wmmute-helper and is placed in /usr/local/bin. This can be overriden by using the -c switch. When invoked, the program gets one argument from wmmute - the actual level. The levels are 0 (mute), 1 (minimum), 2 (medium) and 3 (maximum).

.SH SEE ALSO
.BR wmmute-helper(1)

.SH AUTHOR
Brian Schau <brian@schau.dk>
