package com.schau.ltools;

public class LMETest {
/*
 * This file was generated by $(@userid)/$(@seconds)/$(@ctime) on $(@os).
 *
 * Current PATH: $($PATH)
 *
 * @1A1@
 *
 * Content of PropsFile
 
$(=PropsFile)
 
 * Fun with recursion:
 *
 * $(A)
 * $(B)
 * $(C)
 *
 * $(@filesize src/LMETest.java)
 * $(@filectime this)
 * $(@fileatime src/LMETest.java)
 * $(@filemtime this "%C %m %d")
 * $(!cat /tmp/Windows.c)
 */
	public static void main(String[] args) {
		System.out.println("$(greeting)");
		System.exit(0);
	}
}
