PREFIX	?=	/usr/local

clean:
	-rm -f *~

install:
	sudo cp wmbattery.1 $(PREFIX)/man/man1
	sudo cp wmbrian.1 $(PREFIX)/man/man1
	sudo cp wmbutton.1 $(PREFIX)/man/man1
	sudo cp wmcdrom.1 $(PREFIX)/man/man1
	sudo cp wmclock.1 $(PREFIX)/man/man1
	sudo cp wmmute.1 $(PREFIX)/man/man1
	sudo cp wmmute-helper.1 $(PREFIX)/man/man1
	sudo cp wmshutdown.1 $(PREFIX)/man/man1
	sudo cp wmwireless.1 $(PREFIX)/man/man1
