.TH WMBATTERY 1L "14 November 2010"
.SH NAME
wmbattery \- a dock application showing the battery level

.SH SYNOPSIS
.B wmbattery
[\fI-b battery\fR] [\fI-h\fR]

.SH DESCRIPTION
wmbattery is a dock application which shows the current battery level. This only works for ACPI systems.

.SH OPTIONS
.TP
\fB-b battery\fR
Which battery to monitor (BAT0, BAT1, ...). Default is BAT0.
.TP
\fB-h\fR
Show a small help page.

.SH AUTHOR
Brian Schau <brian@schau.dk>
