.TH WMCDROM 1L "14 November 2010"
.SH NAME
wmcdrom \- dock application to mount and unmount CD or DVD medias

.SH SYNOPSIS
.B wmcdrom
[\fI-b browse\fR] [\fI-e eject\fR] [\fI-h\fR] [\fI-n\fR] [\fI-m mount\fR] [\fI-u umount\fR]
device

.SH DESCRIPTION
wmcdrom is a dock application which can mount and unmount CD or DVD medias in your CD/DVD reader. Use the left mouse button to mount or unmount media.  Use the right button to mount or eject media.

.SH OPTIONS
.TP
\fB-b browse\fR
Full commandline to browse after mount. Default is /usb/bin/thunar /mnt/cdrom.
.TP
\fB-e eject\fR
Path to eject program. Default is /usr/bin/eject.
.TP
\fB-h\fR
Help page.
.TP
\fB-n\fR
Do not browse after mount.
.TP
\fB-m mount\fR
Path to mount program. Default is /bin/mount.
.TP
\fB-u umount\fR
Path to unmount program. Default is /bin/umount.
.TP
\fBdevice\fR
Path to CDRom device node.

.SH AUTHOR
Brian Schau <brian@schau.dk>
