.TH WMWIRELESS 1L "16 November 2010"
.SH NAME
wmwireless \- a dock application to show the signal strength of a wireless interface

.SH SYNOPSIS
.B wmwirless
[\fI-l cmd\fR] [\fI-h\fR] [\fI-r cmd\fR] [\fI-w interface\fR]

.SH DESCRIPTION
wmwireless shows the signal strength of the specified wireless interface. Left and right mouse button click actions can be configured. The default left button action is to launch wicd-client.

.SH OPTIONS
.TP
\fB-l cmd\fR
Command to run on left mouse click.  Default is /usr/bin/wicd-client -n
.TP
\fB-h\fR
Show a small help page.
.TP
\fB-r cmd\fR
Command to run on right mouse click.
.TP
\fB-w interface\fR
Wireless interface to monitor. Default is wlan0.

.SH AUTHOR
Brian Schau <brian@schau.dk>
