#!/bin/bash

# This script controls the sound settings. It will get the requested level in
# $1.
#

function _set_volume
{
	pactl set-sink-mute @DEFAULT_SINK@  $1
	pactl set-sink-volume @DEFAULT_SINK@ $2
}

# Main
#
# Level is in $1
#
case "$1" in
	"0")	# Mute sound
		_set_volume 1 0
		;;

	"1")	# Set minimum level 
		_set_volume 0 33%
		;;

	"2")	# Set medium level
		_set_volume 0 66%
		;;

	"3")	# Set maximum level
		_set_volume 0 100%
		;;

	*)
		echo "Usage: $0 0|1|2|3"
		exit 1
		;;
esac
exit 0
