#!/bin/sh
if test $# -eq 0; then
	echo "Brug: ${0##*/} kolonne [fil]"
	exit 0
fi

kolonne=$1
if test $# -gt 1; then
	fil=$2
else
	fil=/dev/stdin
fi

awk -v kol=$kolonne '
// { sum+=$kol }
END { print sum }' $fil
