#!/bin/bash
if test $# -ne 2; then
	echo "$0 input.mkv output.mp4" >&2
	exit 1
fi

if test ! -s "$1"; then
	echo "$1 does not exist" >&2
	exit
fi

if test -s "$2"; then
	echo "$2 already exists - refusing to overwrite" >&2
	exit 1
fi

avconv -i "$1" -vcodec copy -acodec copy "$2"
exit $?
