#!/bin/bash
#
# mp3cat: http://tomclegg.net/mp3cat
# id3cp: sudo apt-get install libid3-tools
# vbrfix: sudo apt-get install vbrfix
#
if test $# -lt 1; then
	echo "$0 output.mp3" >&2
	exit 1
fi

output="$1"
tmpfile="$(tempfile)"
listfile="$(tempfile)"
trap "rm -f $tmpfile $listfile" 0
find . -iname "*.mp3" | sort > $listfile
master="$(head -n 1 $listfile)"

echo "Concatenating $(cat $listfile | wc -l) files"
while read file; do
	echo "+ adding $file" >&2
	cat $file
done < $listfile | mp3cat - - > "$tmpfile"

echo "Setting ID3 info"
id3cp "$master" "$tmpfile"

echo "Fixing VBR"
vbrfix -always -makevbr -ri1 -ri2 "$tmpfile" "$output"
exit 0
