#!/bin/bash
echo "This little script will rename files in the current directory according"
echo "to these rules:"
echo
echo " - files starting with [digits], [digits space], [digits dash],"
echo "   [digits dash digits] or any combination hereof will have the"
echo "   prefix removed."
echo " - square brackets will also be removed"
echo
echo "Type doit at the prompt to ... well, do it!"
read a
if test "$a" != "doit"; then
	echo "Ok, bye"
	exit 0
fi

ls | while read line; do
	new="$(echo "$line" | tr -d '[]')"
	new="${new#${new%?${new#*[A-Za-z]}}}"
	if test "$new" != "$line"; then
		echo "Renaming $line to $new ..."
		mv "$line" "$new"
	fi
done
exit 0
