#!/bin/bash
#
# This can also be used to join 3gps into mp4
#
if test $# -lt 2; then
	echo "Usage: mp4cat output.mp4 movie1 [movie2 ... movieX]" >&2
	exit 1
fi

bins="MP4Box"
for b in $bins; do
	p="$(type -p $b)"
	if test -z "$p"; then
		echo "$b not found in path" >&2
		exit 1
	fi
done

output="$1"
shift
srcs=""
err="n"
for s; do
	if test -s "$s"; then
		srcs="$srcs -cat $s"
	else
		echo "$s not found!" >&2
		exit 1
	fi
done

MP4Box $srcs $output
exit 0
